#!/system/bin/sh

if [ "$(whoami)" != "root" ];then
	echo -e 'RUN WITH ROOT PERMISSIONS !!!'
	exit 1
fi

if [[ -s /data/media/0/Android/znull.sh ]];then
	chmod +x /data/media/0/Android/znull.sh
	source /data/media/0/Android/znull.sh
else
	echo "Don't delete znull.sh in /Internal/Android!"
	echo "You can edit it, it open source."
	echo "But don't delete it!"
	echo ""
	echo "restoring to default.."
	cp -f /data/adb/modules/znull/libraries/znull.sh /data/media/0/Android/.
	chmod +x /data/media/0/Android/znull.sh
	echo "Done."
	echo "re-run znull if need ;)"
	exit 1
fi

exit